### ISSUE TITLE
不知道能不能增加个精选结点功能

### ISSUE THREAD

**Issue by Jie-Qiao** [Leon406/Sub#4]
结点太多，clash打开直接卡死了哈哈。。能不能测试下真连接，把一些无法用的结点剔除掉？

**Comment by songtao1873** [comment]
> 结点太多，clash打开直接卡死了哈哈。。能不能测试下真连接，把一些无法用的结点剔除掉？

这个就是测试果真链接后的节点, 不过每个人用的宽带和地区不一样, 所以有的人能用, 有的人不能用

**Comment by Leon406** [comment]
本地测试的节点数量只有1000+, github服务器测试,就1W+了,这跟其他节点的一样,显示几千,但是不同网络的可用数量不一样

可以自行clone代码本地运行, 生成当前网络的节点
