### ISSUE TITLE
加一个节点池

### ISSUE THREAD

**Issue by zzysite** [Leon406/Sub#5]
clash订阅链接（需要翻墙订阅） https://raw.githubusercontent.com/chfchf0306/4.18clash/main/Class

v2ray订阅链接（需要翻墙订阅） ：https://raw.githubusercontent.com/chfchf0306/jeidian4.18/main/4.18

**Comment by Leon406** [comment]
感谢提issue, 已经包含再第三方里面了,不再添加
https://github.com/shoujiyanxishe/atu/blob/main/etsub.list
