### ISSUE TITLE
请问这个应该怎么用呢

### ISSUE THREAD

**Issue by carmo2011** [Leon406/Sub#6]
不懂技术，弱弱问下怎么在本地windows电脑上使用呀，自己来筛选节点，以及测速，谢谢

**Comment by Leon406** [comment]
本地服务器筛选(不定时更新) 节点详情,可自行clone项目,执行localFilter.bat生成

localFilter.bat 这个文件在根目录,双击即可执行

**Comment by carmo2011** [comment]
> 本地服务器筛选(不定时更新) 节点详情,可自行clone项目,执行localFilter.bat生成
> 
> localFilter.bat 这个文件在根目录,双击即可执行

执行后就是闪一下，什么都没看到，就退出了
